# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'todd'
outputs:
  time: # id of output
    description: 'The time we greeted you'
    value: ''
runs:
  using: 'composite'
  steps: 
    - run: PARTNER=${{ inputs.partner }} ENVIRONMENT=${{ inputs.environments }} docker-compose up --exit-code-from automation
      id: docker-compose
      shell: bash
    - name: env echo
      run: env
      shell: bash
    - name: ls echo
      run: ls
      shell: bash
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: test-result
    #     path: results.txt