# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: WebDriverIO CI

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e_regression:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Hello world action step
      id: hello
      uses: Todd-j-sutherland/e2e-test@test_v1.1
    - name: SetUp NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: 16.3.0
    
    - name: Run docker-compose 
      run: docker-compose up --exit-code-from automation
  