on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: Todd-j-sutherland/e2e-test@head/test1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step test
      # - uses: actions/checkout@v2
      - name: Run docker-compose 
        run: docker-compose up --exit-code-from automation