on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: Todd-j-sutherland/e2e-test@head/test1
        with:
          who-to-greet: 'Mona the Octocat'
      - name: env echo 1
        run: env
        shell: bash
      - name: ls echo 1
        run: ls
        shell: bash
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: test-result
  #     path: results.txt