on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: Todd-j-sutherland/e2e-test@testing_new
        with:
          who-to-greet: 'Mona the Octocat'
      - name: download the results
        uses: actions/download-artifact@v3
        with:
          name: test-result
      - name: get the test output 
        shell: bash
        run: |
          value=`cat results.txt`
          echo $value