on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: Todd-j-sutherland/e2e-test@m/docker-compose
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step test
      # - uses: actions/checkout@v2
      - name: Get current date
        if: failure()
        id: date
        run: echo "ls ::set-output name=date::$(date +'%Y-%m-%d')"
      - name: get the test output && slack notifications
        if: failure()
        # run: echo "results are in-- ${{ steps.e2e.outputs.result }}"
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_CHANNEL }}
