on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: Todd-j-sutherland/e2e-test@testing_new
        with:
          who-to-greet: 'Mona the Octocat'
      - name: get the results
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "State is: '${{ env.action_state }}'" # No output since same step
      - name: Step 2
        run: |
            echo "State is: '${{ env.action_state }}'" # Output works