on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: Todd-j-sutherland/e2e-test@m/docker-compose
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step test
      # - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: get the test output && slack notifications
        if: failure()
        # run: echo "results are in-- ${{ steps.e2e.outputs.result }}"
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_CHANNEL }}
        with:
          channel-id: "${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_CHANNEL }}"
          payload: |
            {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "You have a new request:\n*<fakeLink.toEmployeeProfile.com|Fred Enriquez - New device request>*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Type:*\nComputer (laptop)"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*When:*\nSubmitted Aut 10"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Reason:*\nAll vowel keys aren't working."
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Specs:*\n\"Cheetah Pro 15\" - Fast, really fast\""
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Approve"
                    },
                    "style": "primary",
                    "value": "click_me_123"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Deny"
                    },
                    "style": "danger",
                    "value": "click_me_123"
                  }
                ]
              }
            ]
            }
