on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: Todd-j-sutherland/e2e-test@m/docker-compose
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step test
      # - uses: actions/checkout@v2
      - name: get the test output && slack notifications
        if: failure()
        # run: echo "results are in-- ${{ steps.e2e.outputs.result }}"
        uses: slackapi/slack-github-action@v1.18.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_CHANNEL }}
        with:
          payload: |
            {
              "text": "Onboarding end-2-end testing",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action test result: : dfdd\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }